import {Role} from './types';

export type Capability='AUTHOR_CONTENT'|'REVIEW_CONTENT'|'EDIT_CONTENT'|'FACT_CHECK'|'SEO_EDIT'|'PUBLISH_CONTENT'|'MANAGE_USERS'|'SYSTEM_ADMIN';

const roleCapabilities:Record<Role,Capability[]>={
 READER:[],CONTRIBUTOR:[],AUTHOR:['AUTHOR_CONTENT'],SENIOR_AUTHOR:['AUTHOR_CONTENT'],
 REVIEWER:['REVIEW_CONTENT'],LANGUAGE_EDITOR:['REVIEW_CONTENT','EDIT_CONTENT'],FACT_CHECKER:['REVIEW_CONTENT','FACT_CHECK'],
 MANAGING_EDITOR:['REVIEW_CONTENT','EDIT_CONTENT','FACT_CHECK','SEO_EDIT'],EDITOR_IN_CHIEF:['REVIEW_CONTENT','EDIT_CONTENT','FACT_CHECK','SEO_EDIT','PUBLISH_CONTENT'],
 PUBLISHER:['REVIEW_CONTENT','EDIT_CONTENT','FACT_CHECK','SEO_EDIT','PUBLISH_CONTENT'],
 ADMINISTRATOR:['AUTHOR_CONTENT','REVIEW_CONTENT','EDIT_CONTENT','FACT_CHECK','SEO_EDIT','PUBLISH_CONTENT','MANAGE_USERS'],
 SYSTEM_ADMINISTRATOR:['AUTHOR_CONTENT','REVIEW_CONTENT','EDIT_CONTENT','FACT_CHECK','SEO_EDIT','PUBLISH_CONTENT','MANAGE_USERS','SYSTEM_ADMIN']
};
export const hasCapability=(role:Role,capability:Capability)=>roleCapabilities[role].includes(capability);
export const canAccessAny=(role:Role,capabilities:Capability[])=>capabilities.some(c=>hasCapability(role,c));
