export const locales = ["id", "en"] as const;
export type Locale = (typeof locales)[number];
export const dictionary = {
  id:{home:"Beranda",latest:"Terbaru",science:"Sains",technology:"Teknologi",education:"Pendidikan",research:"Riset",opinion:"Opini",video:"Video",authors:"Penulis",submit:"Kirim Artikel",login:"Masuk",hero:"Kecerdasan Buatan Mengubah Cara Universitas Melakukan Riset",heroSummary:"Dari analisis data hingga penulisan akademik, AI menciptakan peluang baru sekaligus menuntut standar etika yang lebih kuat.",latestTitle:"Berita Terbaru",researchTitle:"Sorotan Riset",watchTitle:"Tonton Science News",authorsTitle:"Suara Para Ahli"},
  en:{home:"Home",latest:"Latest",science:"Science",technology:"Technology",education:"Education",research:"Research",opinion:"Opinion",video:"Video",authors:"Authors",submit:"Submit Article",login:"Login",hero:"Artificial Intelligence Is Transforming University Research",heroSummary:"From data analysis to academic writing, AI creates new opportunities while demanding stronger ethical standards.",latestTitle:"Latest News",researchTitle:"Research Highlights",watchTitle:"Watch Science News",authorsTitle:"Expert Voices"}
};
export const stories = [
 {slug:"ai-university-research",category:"Artificial Intelligence",titleId:"AI Generatif Mengubah Riset Universitas",titleEn:"Generative AI Transforms University Research",summaryId:"Akademisi menata ulang metode riset, evaluasi sumber, dan integritas publikasi.",summaryEn:"Academics are reshaping research methods, source evaluation, and publication integrity."},
 {slug:"climate-ocean",category:"Climate",titleId:"Laut Menyimpan Sinyal Perubahan Iklim",titleEn:"Oceans Reveal New Climate Signals",summaryId:"Data laut membantu ilmuwan memahami perubahan suhu global.",summaryEn:"Ocean data helps scientists understand changes in global temperature."},
 {slug:"quantum-health",category:"Health Technology",titleId:"Komputasi Kuantum untuk Penemuan Obat",titleEn:"Quantum Computing for Drug Discovery",summaryId:"Simulasi molekul yang lebih cepat membuka jalur baru dalam kesehatan.",summaryEn:"Faster molecular simulations open new pathways in healthcare."},
 {slug:"future-learning",category:"Education",titleId:"Masa Depan Pembelajaran Adaptif",titleEn:"The Future of Adaptive Learning",summaryId:"Teknologi personalisasi mengubah pengalaman belajar mahasiswa.",summaryEn:"Personalization technologies are reshaping student learning experiences."},
 {slug:"space-telescope",category:"Space",titleId:"Teleskop Baru Memetakan Galaksi Jauh",titleEn:"New Telescope Maps Distant Galaxies",summaryId:"Pengamatan terbaru memperluas pemahaman tentang alam semesta awal.",summaryEn:"New observations expand understanding of the early universe."},
 {slug:"green-energy",category:"Energy",titleId:"Terobosan Penyimpanan Energi Hijau",titleEn:"Breakthrough in Green Energy Storage",summaryId:"Baterai generasi baru menjanjikan kapasitas dan keamanan lebih baik.",summaryEn:"Next-generation batteries promise improved capacity and safety."}
];
export const getStoryTitle=(s:typeof stories[number],l:Locale)=>l==="id"?s.titleId:s.titleEn;
export const getStorySummary=(s:typeof stories[number],l:Locale)=>l==="id"?s.summaryId:s.summaryEn;
