export const infoPages:Record<string,{eyebrow:string;title:string;lead:string;sections:{title:string;body:string}[]}>= {
  'author-guidelines':{eyebrow:'CONTRIBUTE',title:'Pedoman Penulis',lead:'Standar praktis untuk mengirim berita sains, artikel ilmiah populer, materi kuliah, tutorial, dan video pembelajaran.',sections:[{title:'Sebelum mengirim',body:'Pastikan artikel orisinal, akurat, memiliki sumber yang dapat diverifikasi, serta tidak sedang melanggar hak cipta pihak lain.'},{title:'Struktur konten',body:'Gunakan judul yang jelas, ringkasan singkat, isi terstruktur, gambar berizin, identitas penulis, afiliasi, referensi, serta disclosure penggunaan AI jika ada.'},{title:'Proses penilaian',body:'Setiap kiriman melalui screening, review editorial, pemeriksaan fakta, revisi bila diperlukan, dan persetujuan publikasi.'}]},
  'editorial-process':{eyebrow:'TRANSPARENCY',title:'Proses Editorial',lead:'Setiap konten melewati alur editorial terkontrol sebelum diterbitkan.',sections:[{title:'1. Submission',body:'Penulis terdaftar membuat draft dan mengirimkannya untuk ditinjau.'},{title:'2. Review',body:'Editor memeriksa relevansi, struktur, akurasi, sumber, media, dan kepatuhan etika.'},{title:'3. Fact checking',body:'Klaim penting, angka, kutipan, referensi, gambar, dan konflik kepentingan diverifikasi.'},{title:'4. Publication',body:'Publisher menjadwalkan dan menerbitkan konten yang telah disetujui. Semua perubahan pascapublikasi tercatat.'}]},
  'editorial-policy':{eyebrow:'TRUST',title:'Kebijakan Editorial',lead:'Independensi, akurasi, transparansi, dan kepentingan publik menjadi dasar seluruh keputusan editorial.',sections:[{title:'Independensi',body:'Keputusan konten tidak boleh ditentukan oleh pengiklan, sponsor, kepentingan politik, atau hubungan pribadi.'},{title:'Akurasi',body:'Informasi harus didukung sumber kredibel dan disajikan dalam konteks yang tepat.'},{title:'Transparansi',body:'Afiliasi, pendanaan, konflik kepentingan, koreksi, dan penggunaan AI harus diungkapkan.'}]},
  'fact-checking':{eyebrow:'TRUST',title:'Pemeriksaan Fakta',lead:'Klaim yang dapat diverifikasi diperiksa sebelum publikasi dan ditinjau ulang apabila terdapat informasi baru.',sections:[{title:'Sumber primer',body:'Kami memprioritaskan jurnal, dataset resmi, dokumen institusi, wawancara langsung, dan publikasi akademik.'},{title:'Klaim berisiko tinggi',body:'Kesehatan, keselamatan, kebijakan publik, keuangan, dan temuan ilmiah sensitif memperoleh pemeriksaan tambahan.'}]},
  'corrections':{eyebrow:'ACCOUNTABILITY',title:'Koreksi & Pembaruan',lead:'Kesalahan diperbaiki secara terbuka tanpa menghapus riwayat editorial.',sections:[{title:'Koreksi ringan',body:'Kesalahan ejaan atau format dapat diperbaiki dengan jejak perubahan internal.'},{title:'Koreksi substansial',body:'Perubahan makna, angka, atau kesimpulan akan disertai catatan pembaruan pada artikel.'},{title:'Retraction',body:'Konten dapat ditarik jika ditemukan fabrikasi, plagiarisme, pelanggaran etika, atau risiko publik yang serius.'}]},
  'ai-policy':{eyebrow:'RESPONSIBLE AI',title:'Kebijakan Penggunaan AI',lead:'AI dapat membantu pekerjaan editorial, tetapi manusia tetap bertanggung jawab atas seluruh konten.',sections:[{title:'Pengungkapan',body:'Penggunaan AI yang material dalam pembuatan teks, gambar, analisis, atau penerjemahan harus dinyatakan.'},{title:'Larangan',body:'AI tidak boleh digunakan untuk membuat sumber palsu, memalsukan data, meniru narasumber, atau menyembunyikan plagiarisme.'}]},
  'privacy':{eyebrow:'DATA PROTECTION',title:'Kebijakan Privasi',lead:'Kami mengumpulkan data minimum yang diperlukan untuk memberikan layanan dan melindungi akun.',sections:[{title:'Data akun',body:'Nama, email, afiliasi, profil penulis, dan aktivitas editorial digunakan sesuai fungsi platform.'},{title:'Analytics',body:'Data penggunaan dapat dianalisis secara agregat untuk memperbaiki pengalaman pembaca dan performa konten.'}]},
  'about':{eyebrow:'COMPANY',title:'Tentang Science News 360',lead:'Platform media pengetahuan yang menghubungkan berita sains, akademisi, riset, video, dan pembelajaran perguruan tinggi.',sections:[{title:'Misi',body:'Membuat pengetahuan ilmiah lebih akurat, mudah dipahami, terbuka, dan bermanfaat bagi masyarakat global.'},{title:'Ruang lingkup',body:'Sains, teknologi, pendidikan, ekonomi, manajemen, akuntansi, ekonomi Islam, metodologi penelitian, seni, dan pengetahuan umum.'}]},
  'partners':{eyebrow:'COLLABORATION',title:'Mitra & Institusi',lead:'Kami membuka kolaborasi dengan universitas, jurnal, laboratorium, komunitas, lembaga publik, dan organisasi pengetahuan.',sections:[{title:'Kolaborasi konten',body:'Publikasi hasil riset, expert commentary, materi kuliah, webinar, dan video pembelajaran.'},{title:'Kemitraan institusi',body:'Profil institusi, kanal tematik, program literasi, dan kegiatan ilmiah bersama.'}]},
  'careers':{eyebrow:'JOIN US',title:'Karier',lead:'Bangun ekosistem pengetahuan bersama editor, penulis, fact-checker, desainer, pengembang, dan pengelola komunitas.',sections:[{title:'Kesempatan',body:'Lowongan dan program kontributor akan diumumkan melalui halaman ini.'},{title:'Budaya kerja',body:'Akurat, kolaboratif, terbuka terhadap pembelajaran, dan bertanggung jawab terhadap publik.'}]},
  'contact':{eyebrow:'CONTACT',title:'Hubungi Kami',lead:'Sampaikan pertanyaan editorial, koreksi, kerja sama, atau dukungan teknis melalui saluran resmi.',sections:[{title:'Editorial',body:'Untuk pitching dan pertanyaan artikel, gunakan dashboard penulis atau formulir pengiriman.'},{title:'Partnership',body:'Untuk kerja sama institusi dan media, sertakan tujuan, ruang lingkup, serta kontak penanggung jawab.'},{title:'Corrections',body:'Sertakan URL artikel, bagian yang dipermasalahkan, bukti pendukung, dan penjelasan koreksi.'}]}
};
