'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';

type SavedVideo={id:string;title:string;url:string;videoId:string;thumbnail:string};
function extractVideoId(value:string){try{const u=new URL(value);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||'';}catch{return value.trim().match(/^[\w-]{11}$/)?.[0]||'';}}
export function YouTubeAdminSettings(){
 const [channel,setChannel]=useState('https://www.youtube.com/@sciencenews360'); const [channelId,setChannelId]=useState(''); const [apiKey,setApiKey]=useState('');
 const [url,setUrl]=useState(''); const [title,setTitle]=useState(''); const [videos,setVideos]=useState<SavedVideo[]>([]); const videoId=useMemo(()=>extractVideoId(url),[url]);
 useEffect(()=>{try{setChannel(localStorage.getItem('sn360-youtube-channel')||'https://www.youtube.com/@sciencenews360');setChannelId(localStorage.getItem('sn360-youtube-channel-id')||'');const raw=localStorage.getItem('sn360-youtube-videos');if(raw)setVideos(JSON.parse(raw));}catch{}},[]);
 function saveChannel(){localStorage.setItem('sn360-youtube-channel',channel);localStorage.setItem('sn360-youtube-channel-id',channelId);alert('Pengaturan channel berhasil disimpan.');}
 function addVideo(e:FormEvent){e.preventDefault();if(!videoId||!title.trim())return alert('Masukkan URL YouTube yang valid dan judul video.');const next=[{id:crypto.randomUUID(),title:title.trim(),url,videoId,thumbnail:`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`},...videos];setVideos(next);localStorage.setItem('sn360-youtube-videos',JSON.stringify(next));setUrl('');setTitle('');}
 function remove(id:string){const next=videos.filter(v=>v.id!==id);setVideos(next);localStorage.setItem('sn360-youtube-videos',JSON.stringify(next));}
 return <div className="youtube-admin-grid"><section className="admin-panel youtube-setup"><span className="eyebrow">PENGATURAN CHANNEL</span><h2>Hubungkan Channel YouTube</h2><p>Masukkan alamat channel YouTube. Pengaturan lanjutan hanya diperlukan bila Anda ingin menampilkan video terbaru secara otomatis.</p><label>URL Channel<input value={channel} onChange={e=>setChannel(e.target.value)} placeholder="https://www.youtube.com/@sciencenews360"/></label><label>Kode Channel <small>(opsional)</small><input value={channelId} onChange={e=>setChannelId(e.target.value)} placeholder="UCxxxxxxxxxxxxxxxxxxxxxx"/></label><label>Kunci Akses YouTube <small>(opsional)</small><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type="password" placeholder="Masukkan hanya saat fitur otomatis digunakan"/></label><div className="youtube-admin-actions"><button className="btn btn-primary" onClick={saveChannel}>Simpan Channel</button><a className="btn btn-secondary" href={channel} target="_blank" rel="noreferrer">Lihat Channel ↗</a></div><div className="youtube-security-note"><b>Catatan</b><span>Jangan membagikan kunci akses kepada pihak lain.</span></div></section><section className="admin-panel youtube-single-video"><span className="eyebrow">SATU VIDEO</span><h2>Tambahkan Video YouTube</h2><p>Tempel URL video. Gambar sampul akan muncul otomatis setelah tautan dikenali.</p><form onSubmit={addVideo}><label>URL Video<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/></label><label>Judul di Website<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Judul video pembelajaran"/></label>{videoId&&<div className="youtube-preview"><img src={`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`} alt="Pratinjau video"/><div><b>Gambar sampul berhasil dikenali</b><small>Video siap ditambahkan.</small></div></div>}<button className="btn btn-dark" type="submit">＋ Tambahkan Video</button></form></section><section className="admin-panel youtube-saved"><div className="admin-panel-title"><div><span className="eyebrow">VIDEO TERSIMPAN</span><h2>Video Terhubung</h2></div><b>{videos.length}</b></div>{videos.length===0?<div className="youtube-empty">Belum ada video YouTube yang ditambahkan.</div>:<div className="youtube-saved-list">{videos.map(v=><article key={v.id}><img src={v.thumbnail} alt=""/><div><strong>{v.title}</strong><small>{v.videoId}</small><a href={v.url} target="_blank" rel="noreferrer">Buka ↗</a></div><button onClick={()=>remove(v.id)} aria-label={`Hapus ${v.title}`}>×</button></article>)}</div>}</section></div>
}
