import Link from "next/link";
import {notFound} from "next/navigation";

const profiles:any={
 aiyub:{name:"Aiyub, S.E., M.Ec., Ph.D.",initials:"AA",role:"Economics & Digital Science",institution:"Universitas Malikussaleh",bio:"Akademisi dan penulis yang berfokus pada ekonomi pembangunan, kepemimpinan digital, analisis data, teknologi, serta pembelajaran perguruan tinggi.",topics:["Ekonomi Pembangunan","Kepemimpinan Digital","Metodologi Penelitian","Analisis Data"]},
 "nadia-rahman":{name:"Nadia Rahman, Ph.D.",initials:"NR",role:"Public Health",institution:"Global Health Institute",bio:"Peneliti kesehatan publik dan komunikator sains.",topics:["Public Health","Medical Evidence","Science Communication"]},
 "david-chen":{name:"David Chen, Ph.D.",initials:"DC",role:"Artificial Intelligence",institution:"Institute for Advanced Computing",bio:"Peneliti komputasi yang menulis tentang AI dan teknologi kuantum.",topics:["Artificial Intelligence","Quantum Computing","Research Technology"]},
 "maria-alvarez":{name:"Maria Alvarez, Ph.D.",initials:"MA",role:"Climate Research",institution:"Ocean & Climate Research Center",bio:"Ilmuwan iklim yang membahas laut, lingkungan, dan kebijakan.",topics:["Climate","Ocean Science","Environmental Policy"]},
 "samuel-okoro":{name:"Samuel Okoro, Ph.D.",initials:"SO",role:"Energy & Development",institution:"African Energy Futures Lab",bio:"Analis energi dan pembangunan berkelanjutan.",topics:["Energy","Innovation","Sustainable Development"]},
 "lina-putri":{name:"Lina Putri, M.Sc.",initials:"LP",role:"Digital Education",institution:"ASEAN Learning Innovation Network",bio:"Praktisi pendidikan digital dan learning analytics.",topics:["Digital Learning","Learning Analytics","Higher Education"]}
};
export function generateStaticParams(){return Object.keys(profiles).flatMap(slug=>["id","en"].map(locale=>({locale,slug})));}
export default async function AuthorProfile({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const p=profiles[slug];if(!p)notFound();const id=locale!=="en";return <main className="author-detail-page"><section className="author-detail-hero"><div className="shell author-detail-grid"><div className="author-avatar-xl">{p.initials}</div><div><span>{id?"PROFIL PENULIS":"AUTHOR PROFILE"}</span><h1>{p.name}</h1><p className="author-detail-role">{p.role} · {p.institution}</p><p>{p.bio}</p><div className="author-topic-row">{p.topics.map((t:string)=><b key={t}>{t}</b>)}</div></div><aside><strong>12</strong><small>{id?"Artikel terbit":"Published articles"}</small><strong>184K</strong><small>{id?"Total pembaca":"Total readers"}</small></aside></div></section><section className="shell author-detail-content"><div><span>{id?"ARTIKEL TERBARU":"LATEST STORIES"}</span><h2>{id?"Karya pilihan penulis":"Selected work"}</h2></div><div className="author-story-list">{["Kecerdasan Buatan Mengubah Cara Universitas Menemukan Pengetahuan Baru","Transformasi Digital dan Masa Depan Pembelajaran Tinggi","Ekonomi Pembangunan dalam Era Data dan AI"].map((t,i)=><article key={t}><span>0{i+1}</span><div><small>{i===0?"Artificial Intelligence":"Education & Research"}</small><h3>{t}</h3><p>{id?"Analisis mendalam dan mudah dipahami untuk pembaca akademik dan masyarakat umum.":"Accessible analysis for academic and general audiences."}</p></div></article>)}</div><Link href={`/${locale}/authors`} className="back-authors">← {id?"Kembali ke semua penulis":"Back to all authors"}</Link></section></main>}
