'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useAuth} from '@/components/auth/AuthProvider';

type MenuItem={label:string;href:string;description?:string};
type Menu={label:string;items:MenuItem[]};
const localizedMenus=(locale:'id'|'en'):Menu[]=>[
 {label:locale==='id'?'Sains':'Science',items:[
  {label:locale==='id'?'Biologi':'Biology',href:'biology'},{label:locale==='id'?'Fisika':'Physics',href:'physics'},{label:locale==='id'?'Kesehatan dan Kedokteran':'Health & Medicine',href:'health-and-medicine'},{label:'Climate',href:'climate'},{label:locale==='id'?'Antariksa dan Astronomi':'Space & Astronomy',href:'space-and-astronomy'},{label:locale==='id'?'Ilmu Bumi':'Earth Science',href:'earth-science'}]},
 {label:locale==='id'?'Teknologi':'Technology',items:[
  {label:locale==='id'?'Kecerdasan Buatan':'Artificial Intelligence',href:'artificial-intelligence'},{label:'Robotics',href:'robotics'},{label:locale==='id'?'Komputasi Kuantum':'Quantum Computing',href:'quantum-computing'},{label:'Cybersecurity',href:'cybersecurity'},{label:'Blockchain',href:'blockchain'},{label:'Biotechnology',href:'biotechnology'}]},
 {label:locale==='id'?'Pendidikan':'Education',items:[
  {label:locale==='id'?'Materi Kuliah':'Course Materials',href:'/education/course-materials',description:locale==='id'?'Materi berdasarkan fakultas, program studi, mata kuliah, dan semester.':'Materials organized by faculty, study program, course, and semester.'},
  {label:locale==='id'?'Modul Pembelajaran':'Learning Modules',href:'/education/course-materials?type=learning-module'},
  {label:locale==='id'?'Tutorial Akademik':'Academic Tutorials',href:'/education/course-materials?type=tutorial'},
  {label:locale==='id'?'Video Pembelajaran':'Learning Videos',href:'/education/course-materials?type=learning-video'},
  {label:locale==='id'?'Pendidikan Tinggi':'Higher Education',href:'higher-education'},{label:locale==='id'?'Metodologi Penelitian':'Research Methods',href:'research-methods'}]},
 {label:locale==='id'?'Riset':'Research',items:[
  {label:locale==='id'?'Berita Riset':'Research News',href:'research-news'},{label:locale==='id'?'Publikasi Baru':'New Publications',href:'new-publications'},{label:locale==='id'?'Data dan Visualisasi':'Data & Visualization',href:'data-and-visualization'},{label:locale==='id'?'Pendanaan':'Funding',href:'funding'},{label:locale==='id'?'Kolaborasi':'Collaboration',href:'collaboration'},{label:'Call for Papers',href:'call-for-papers'}]},
 {label:locale==='id'?'Opini':'Opinion',items:[
  {label:locale==='id'?'Opini Pakar':'Expert Opinion',href:'expert-opinion'},{label:'Editorial',href:'editorial'},{label:'Commentary',href:'commentary'},{label:locale==='id'?'Analisis Kebijakan':'Policy Analysis',href:'policy-analysis'},{label:locale==='id'?'Sains dan Masyarakat':'Science & Society',href:'science-and-society'}]}
];
export default function EnterpriseHeader({locale}:{locale:'id'|'en'}){
 const menus=localizedMenus(locale);const {user,logout}=useAuth();const router=useRouter();const [theme,setTheme]=useState('light');const [search,setSearch]=useState(false);const [searchText,setSearchText]=useState('');const [mobile,setMobile]=useState(false);
 useEffect(()=>{const t=localStorage.getItem('sn360-theme')||'light';setTheme(t);document.documentElement.dataset.theme=t},[]);
 const toggle=()=>{const t=theme==='dark'?'light':'dark';setTheme(t);localStorage.setItem('sn360-theme',t);document.documentElement.dataset.theme=t};
 const hrefFor=(href:string)=>href.startsWith('/')?`/${locale}${href}`:`/${locale}/category/${href}`;
 const submitSearch=(e:FormEvent)=>{e.preventDefault();const q=searchText.trim();if(!q)return;setSearch(false);router.push(`/${locale}/latest?q=${encodeURIComponent(q)}`)};
 return <>
  <div className="topline"><div className="shell topflex"><span>SCIENCE NEWS 360 • KNOWLEDGE WITHOUT BORDERS</span><span className="toplinks"><a href="https://www.youtube.com/@sciencenews360" target="_blank" rel="noreferrer">YouTube</a> · <a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a></span></div></div>
  <header className="enterprise-header"><div className="shell header-main">
   <Link href={`/${locale}`} className="brand"><span className="brand-orbit">360</span><span><b>SCIENCE NEWS</b><small>GLOBAL KNOWLEDGE NETWORK</small></span></Link>
   <nav className="desktop-nav"><Link href={`/${locale}`}>{locale==='id'?'Beranda':'Home'}</Link>{menus.map(m=><div className="nav-group" key={m.label}><button type="button" aria-haspopup="true">{m.label}<span aria-hidden="true">⌄</span></button><div className="mega"><div><p className="mega-kicker">EXPLORE {m.label.toUpperCase()}</p><h3>{m.label}</h3><p>{locale==='id'?'Berita tepercaya, materi akademik, sorotan riset, dan wawasan pakar.':'Trusted reporting, academic learning, research highlights, and expert insight.'}</p></div><div className="mega-links">{m.items.map(x=><Link key={x.label} href={hrefFor(x.href)} className={x.href.includes('course-materials')?'mega-learning-link':''}><span><b>{x.label}</b>{x.description&&<small>{x.description}</small>}</span><i>→</i></Link>)}</div><div className="mega-feature"><div className="mini-visual">SN360</div><b>{m.label=== (locale==='id'?'Pendidikan':'Education')?(locale==='id'?'Academic Learning Center':'Academic Learning Center'):(locale==='id'?'Ringkasan editor':'Editor’s briefing')}</b><p>{m.label=== (locale==='id'?'Pendidikan':'Education')?(locale==='id'?'Materi kuliah untuk Ekonomi Pembangunan, Manajemen, Akuntansi, Ekonomi Islam, dan bidang umum lainnya.':'Course materials for economics, management, accounting, Islamic economics, and other disciplines.'):(locale==='id'?'Perkembangan penting yang membentuk ilmu pengetahuan pekan ini.':'The essential developments shaping science this week.')}</p></div></div></div>)}<Link href={`/${locale}/video`}>Video</Link><Link href={`/${locale}/authors`}>{locale==='id'?'Penulis':'Authors'}</Link></nav>
   <div className="header-tools"><button type="button" aria-label="Cari" onClick={()=>setSearch(true)}>⌕</button><button type="button" aria-label="Ubah tampilan" onClick={toggle}>{theme==='dark'?'☀':'◐'}</button><Link className="language" href={`/${locale==='id'?'en':'id'}`}>{locale==='id'?'EN':'ID'}</Link>{user?<><Link className="user-chip" href={user.role==='ADMINISTRATOR'?'/dashboard/admin':user.role==='SYSTEM_ADMINISTRATOR'?'/dashboard/system-admin':'/dashboard/author'}>{user.name}</Link><button type="button" aria-label="Keluar" onClick={logout}>↪</button></>:<><Link className="login-link" href={`/${locale}/login`}>{locale==='id'?'Masuk':'Sign in'}</Link><Link className="author-register-link" href={`/${locale}/register`}>{locale==='id'?'Daftar Penulis':'Author Sign-up'}</Link></>}<Link className="submit" href={user?'/dashboard/author/create':`/${locale}/login?next=${encodeURIComponent('/dashboard/author/create')}`}>{locale==='id'?'Kirim Artikel':'Submit Article'}</Link><button type="button" className="hamburger" onClick={()=>setMobile(!mobile)}>☰</button></div>
  </div></header>
  {mobile&&<div className="mobile-menu">{menus.map(m=><details key={m.label}><summary>{m.label}</summary>{m.items.map(x=><Link key={x.label} href={hrefFor(x.href)}>{x.label}</Link>)}</details>)}<Link href={`/${locale}/video`}>Video</Link><Link href={`/${locale}/authors`}>{locale==='id'?'Penulis':'Authors'}</Link><Link href={user?'/dashboard/author/create':`/${locale}/login?next=${encodeURIComponent('/dashboard/author/create')}`}>{locale==='id'?'Kirim Artikel':'Submit Article'}</Link></div>}
  {search&&<div className="search-overlay" role="dialog" aria-modal="true" aria-label="Pencarian Science News 360"><button type="button" className="search-close" onClick={()=>setSearch(false)}>×</button><div className="search-panel"><span>PENCARIAN</span><h2>{locale==='id'?'Temukan pengetahuan yang Anda perlukan':'Find the knowledge you need'}</h2><form className="search-box" onSubmit={submitSearch}><input autoFocus value={searchText} onChange={e=>setSearchText(e.target.value)} placeholder={locale==='id'?'Cari artikel, materi kuliah, video, penulis...':'Search articles, course materials, videos, authors...'}/><button type="submit">{locale==='id'?'Cari':'Search'}</button></form><div className="search-suggestions"><b>{locale==='id'?'Pencarian populer:':'Popular:'}</b> Artificial Intelligence · Ekonomi Makro · Metodologi Penelitian · Climate Change</div></div></div>}
 </>
}
