'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {homeData,Locale,Story} from '@/lib/home-data';
import PublishedContentFeed from '@/components/cms/PublishedContentFeed';

const Card=({s,locale,compact=false}:{s:Story;locale:Locale;compact?:boolean})=><article className={compact?'story-card compact':'story-card'}><Link href={`/${locale}/article/${s.slug}`} className="story-image"><img src={s.image} alt={s.title}/><span>{s.category}</span></Link><div className="story-copy"><Link href={`/${locale}/article/${s.slug}`}><h3>{s.title}</h3></Link>{!compact&&<p>{s.summary}</p>}<small>{s.author} · {s.time}</small></div></article>;

export default function HomeSections({locale}:{locale:Locale}){
 const d=homeData[locale];
 const [saved,setSaved]=useState(false);
 const [subscribed,setSubscribed]=useState(false);
 function subscribe(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubscribed(true)}
 return <main>
 <section className="breaking" aria-label={locale==='id'?'Berita langsung':'Live updates'}><div className="shell ticker"><b>LIVE</b><div className="ticker-viewport"><div className="ticker-track"><span>New research • AI and university discovery</span><span>Climate resilience • Cities prepare for extreme heat</span><span>Space science • Next-generation observatory begins tests</span></div></div></div></section>
 <section className="shell hero-grid"><article className="hero-main"><img src={d.hero.image} alt={d.hero.title}/><div className="hero-shade"></div><div className="hero-content"><span>{d.hero.category}</span><h1>{d.hero.title}</h1><p>{d.hero.summary}</p><div className="hero-meta">{d.hero.author} · {d.hero.institution} · {d.hero.time}</div><div className="hero-actions"><Link href={`/${locale}/article/${d.hero.slug}`}>{locale==='id'?'Baca Selengkapnya':'Read Story'} →</Link><button type="button" aria-pressed={saved} onClick={()=>setSaved(v=>!v)}>{saved?'★ Tersimpan':'♡ Bookmark'}</button><a target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent(d.hero.title+' '+'https://sciencenews360-my-id.netlify.app/'+locale+'/article/'+d.hero.slug)}`}>↗ WhatsApp</a></div></div></article>
 <div className="hero-side">{d.secondary.map(s=><Card s={s} locale={locale} compact key={s.slug}/>)}</div></section>
 <PublishedContentFeed locale={locale}/><section className="shell section"><div className="section-head"><div><span>01 / LATEST</span><h2>{locale==='id'?'Riset dan Berita Terbaru':'Latest Research & News'}</h2></div><Link href={`/${locale}/latest`}>{locale==='id'?'Lihat Semua':'View All'} →</Link></div><div className="news-grid">{d.latest.map(s=><Card key={s.slug} s={s} locale={locale}/>)}</div></section>
 <section className="dark-section"><div className="shell"><div className="section-head light"><div><span>02 / WATCH SCIENCE</span><h2>{locale==='id'?'Pengetahuan dalam Gerak':'Knowledge in Motion'}</h2></div><Link href={`/${locale}/video`}>YouTube Channel →</Link></div><div className="video-layout"><div className="video-feature"><Link href={`/${locale}/video`} className="video-screen" aria-label={locale==='id'?'Buka video unggulan':'Open featured video'}><img src="/images/quantum.svg" alt={locale==='id'?'Ilustrasi komputasi kuantum':'Quantum computing illustration'}/><span className="video-play">▶</span></Link><h3>{locale==='id'?'Bagaimana komputasi kuantum akan mengubah penelitian?':'How will quantum computing transform research?'}</h3><p>Science News 360 Explainer · 12:48</p></div><div className="video-list">{d.secondary.slice(0,3).map(s=><Card key={s.slug} s={s} locale={locale} compact/>)}</div></div></div></section>
 <section className="shell section split-section"><div><div className="section-head"><div><span>03 / TRENDING</span><h2>{locale==='id'?'Topik yang Membentuk Masa Depan':'Topics Shaping the Future'}</h2></div></div><div className="topic-cloud">{d.topics.map((x,i)=><Link key={x} href={`/${locale}/topic/${x.toLowerCase().replaceAll(' ','-')}`}><b>0{i+1}</b>{x}<span>↗</span></Link>)}</div></div><aside className="popular-panel"><span>MOST READ THIS WEEK</span>{d.latest.slice(0,5).map((s,i)=><Link key={s.slug} href={`/${locale}/article/${s.slug}`}><b>{String(i+1).padStart(2,'0')}</b><div><em>{s.category}</em><h4>{s.title}</h4></div></Link>)}</aside></section>
 <section className="institution-band"><div className="shell"><span>GLOBAL RESEARCH NETWORK</span><div className="institution-row">{d.institutions.map(x=><div key={x}>{x}</div>)}</div></div></section>
 <section className="shell section"><div className="section-head"><div><span>04 / EXPERT VOICES</span><h2>{locale==='id'?'Penulis dan Pakar Pilihan':'Featured Authors & Experts'}</h2></div><Link href={`/${locale}/authors`}>Directory →</Link></div><div className="author-grid">{d.authors.map((a,i)=><article key={a.name}><Link href={`/${locale}/authors/${i===0?'aiyub':i===1?'nadia-rahman':'david-chen'}`} className="author-avatar" aria-label={`Profil ${a.name}`}>{a.initials}</Link><h3>{a.name}</h3><p>{a.role}</p><Link className="author-follow-link" href={`/${locale}/authors`}>{locale==='id'?'Lihat profil':'View profile'} →</Link></article>)}</div></section>
 <section className="buletin"><div className="shell buletin-inner"><div><span>THE WEEKLY 360</span><h2>{locale==='id'?'Sains penting. Tanpa kebisingan.':'Essential science. Without the noise.'}</h2><p>{locale==='id'?'Ringkasan berita, riset, dan gagasan terbaik setiap pekan.':'A weekly briefing of the most important news, research, and ideas.'}</p></div>{subscribed?<div className="buletin-success" role="status">✓ {locale==='id'?'Terima kasih. Pendaftaran buletin berhasil.':'Thank you. Your buletin signup was recorded in this prototype.'}</div>:<form onSubmit={subscribe}><label className="sr-only" htmlFor="buletin-email">Email</label><input id="buletin-email" required type="email" placeholder="Alamat email"/><button type="submit">{locale==='id'?'Berlangganan':'Subscribe'} →</button></form>}</div></section>
 </main>
}
