'use client';
import {ChangeEvent,useEffect,useRef,useState} from 'react';
import {BackupPayload,downloadBackup,migrateLegacyStorage,restoreBackup,summarizeBackup,validateBackup} from '@/lib/cms/backup';

type Props={onRestored?:()=>void};
export default function BackupManager({onRestored}:Props){
 const input=useRef<HTMLInputElement>(null);const [candidate,setCandidate]=useState<BackupPayload|null>(null);const [notice,setNotice]=useState('');const [migrated,setMigrated]=useState<string[]>([]);
 useEffect(()=>{try{const result=migrateLegacyStorage();setMigrated(result)}catch{}},[]);
 function exportNow(){const b=downloadBackup();setNotice(`Backup berhasil dibuat: ${b.data.content.length} konten, ${b.data.media.length} media.`)}
 async function pick(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const parsed=validateBackup(JSON.parse(await file.text()));setCandidate(parsed);setNotice('File backup valid. Periksa ringkasan sebelum memulihkan.')}catch(err){setCandidate(null);setNotice(err instanceof Error?err.message:'Backup gagal dibaca.')}}
 function restore(mode:'merge'|'replace'){if(!candidate)return;const message=mode==='replace'?'Ganti seluruh data lokal dengan isi backup? Data saat ini akan ditimpa.':'Gabungkan backup dengan data saat ini? Konten dengan ID yang sama akan memakai versi dari backup.';if(!confirm(message))return;try{const result=restoreBackup(candidate,mode);setNotice(`Pemulihan berhasil. ${result.content} konten dan ${result.media} media tersedia.`);setCandidate(null);onRestored?.()}catch(err){setNotice(err instanceof Error?err.message:'Pemulihan gagal.')}}
 const summary=candidate?summarizeBackup(candidate):null;
 return <section className="backup-manager" aria-label="Backup dan pemulihan konten"><div className="backup-copy"><span className="eyebrow">CADANGAN KONTEN</span><h2>Cadangan dan Pemulihan</h2><p>Ekspor pekerjaan sebelum berpindah folder atau port. Impor kembali untuk memulihkan draft, status editorial, riwayat versi, profil, SEO, dan metadata media.</p>{migrated.length>0&&<p className="backup-success">Data versi lama terdeteksi dan dimigrasikan: {migrated.join(', ')}.</p>}{notice&&<p className="backup-notice" role="status">{notice}</p>}</div><div className="backup-actions"><button className="btn btn-secondary" onClick={exportNow}>↓ Unduh Cadangan</button><button className="btn btn-primary" onClick={()=>input.current?.click()}>↑ Pulihkan Cadangan</button><input ref={input} hidden type="file" accept="application/json,.json" onChange={pick}/></div>{summary&&<div className="restore-preview"><div><span className="eyebrow">RESTORE PREVIEW</span><h3>{summary.content} konten siap dipulihkan</h3><p>Dibuat {new Date(summary.exportedAt).toLocaleString('id-ID')} dari <code>{summary.origin}</code>.</p></div><div className="restore-stats"><span><b>{summary.content}</b> Konten</span><span><b>{summary.media}</b> Media</span><span><b>{summary.audit}</b> Audit</span><span><b>{summary.seoRecords}</b> SEO</span></div><div className="restore-statuses">{Object.entries(summary.status).map(([key,value])=><span key={key}>{key}: <b>{value}</b></span>)}</div><div className="restore-buttons"><button className="btn btn-secondary" onClick={()=>restore('merge')}>Gabungkan Data</button><button className="btn btn-danger" onClick={()=>restore('replace')}>Ganti Semua Data</button><button className="btn btn-ghost" onClick={()=>setCandidate(null)}>Batal</button></div></div>}</section>
}
