'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {ContentRecord,ContentType,MediaMeta} from '@/lib/cms/types';
import {getContent,saveContent,saveMedia} from '@/lib/cms/store';
import {prepareImage,MAX_INLINE} from '@/lib/cms/media';
import {stepLabels,validateContent,validateStep} from '@/lib/cms/validation';
import {useAuth} from '@/components/auth/AuthProvider';

const typeLabels:Record<ContentType,string>={SCIENCE_NEWS:'Berita Sains',POPULAR_ARTICLE:'Artikel Ilmiah Populer',RESEARCH_HIGHLIGHT:'Research Highlight',OPINION:'Opini',COURSE_MATERIAL:'Materi Kuliah',LEARNING_MODULE:'Modul Pembelajaran',ACADEMIC_TUTORIAL:'Tutorial Akademik',LEARNING_VIDEO:'Video Pembelajaran',INSTITUTION_NEWS:'Berita Institusi'};
const templates:Record<ContentType,string>={SCIENCE_NEWS:'<h2>Perkembangan utama</h2><p>Tulis lead berita yang menjawab apa, siapa, kapan, di mana, mengapa, dan bagaimana.</p><h2>Mengapa temuan ini penting?</h2><p>Jelaskan dampak bagi pembaca.</p><h2>Apa berikutnya?</h2><p>Tutup dengan konteks dan tindak lanjut.</p>',POPULAR_ARTICLE:'<h2>Pendahuluan</h2><p>Perkenalkan persoalan dengan bahasa yang mudah dipahami.</p><h2>Konsep utama</h2><p>Jelaskan bukti, contoh, dan implikasi.</p><h2>Kesimpulan</h2><p>Rangkum pesan utama.</p>',RESEARCH_HIGHLIGHT:'<h2>Latar belakang penelitian</h2><p></p><h2>Metode</h2><p></p><h2>Temuan utama</h2><p></p><h2>Implikasi</h2><p></p><h2>Keterbatasan</h2><p></p>',OPINION:'<h2>Posisi utama</h2><p></p><h2>Argumentasi</h2><p></p><h2>Bukti dan contoh</h2><p></p><h2>Penutup</h2><p></p>',COURSE_MATERIAL:'<h2>Capaian pembelajaran</h2><ul><li></li></ul><h2>Konsep inti</h2><p></p><h2>Contoh penerapan</h2><p></p><h2>Latihan</h2><ol><li></li></ol><h2>Ringkasan</h2><p></p>',LEARNING_MODULE:'<h2>Identitas modul</h2><p></p><h2>Capaian pembelajaran</h2><p></p><h2>Materi</h2><p></p><h2>Aktivitas belajar</h2><p></p><h2>Evaluasi</h2><p></p>',ACADEMIC_TUTORIAL:'<h2>Tujuan tutorial</h2><p></p><h2>Persiapan</h2><p></p><h2>Langkah 1</h2><p></p><h2>Langkah 2</h2><p></p><h2>Pemeriksaan hasil</h2><p></p>',LEARNING_VIDEO:'<h2>Tujuan video</h2><p></p><h2>Ringkasan isi</h2><p></p><h2>Poin penting</h2><ul><li></li></ul><h2>Latihan dan refleksi</h2><p></p>',INSTITUTION_NEWS:'<h2>Informasi utama</h2><p></p><h2>Latar belakang kegiatan</h2><p></p><h2>Dampak dan tindak lanjut</h2><p></p>'};
const slugify=(x:string)=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90);
const youtubeId=(url:string)=>url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([A-Za-z0-9_-]{6,})/)?.[1]||'';
const initial=(name='',email=''):ContentRecord=>({id:crypto.randomUUID(),title:'',subtitle:'',summary:'',bodyHtml:'',type:'POPULAR_ARTICLE',status:'DRAFT',locale:'id',faculty:'Ekonomi dan Bisnis',studyProgram:'Ekonomi Pembangunan',course:'',degree:'Sarjana',semester:'',topic:'',inlineMedia:[],videoMethod:'NONE',authors:[{name,email,affiliation:'',role:'PRIMARY'}],references:'',doi:'',funding:'',conflict:'',aiDisclosure:'',seoTitle:'',seoDescription:'',focusKeyword:'',slug:'',internalLinks:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),versions:[]});
export default function ContentWizard(){
 const {user}=useAuth();const router=useRouter();const search=useSearchParams();const editor=useRef<HTMLDivElement>(null);const [step,setStep]=useState(()=>Number(search.get('step')||0));const editId=search.get('edit');const [record,setRecord]=useState<ContentRecord>(()=>initial(user?.name,user?.email));const [notice,setNotice]=useState<{type:'success'|'error'|'info';text:string}|null>(null);const [busy,setBusy]=useState(false);const [saved,setSaved]=useState('Belum disimpan');
 const update=(patch:Partial<ContentRecord>)=>setRecord(v=>({...v,...patch}));
 useEffect(()=>{if(editId){const existing=getContent(editId);if(existing){setRecord(existing);setSaved('Artikel dimuat untuk diedit');return}}try{const p=JSON.parse(localStorage.getItem('sn360-author-profile')||'{}');setRecord(v=>({...v,authors:[{...v.authors[0],name:p.name||user?.name||v.authors[0].name,email:user?.email||v.authors[0].email,affiliation:p.institution||v.authors[0].affiliation,orcid:p.orcid||'',googleScholar:p.googleScholar||'',website:p.website||'',photo:p.photo||''}]}))}catch{}},[user,editId]);
 useEffect(()=>{const type=search.get('type');if(type){const found=Object.entries(typeLabels).find(([,label])=>label===type)?.[0] as ContentType|undefined;if(found)selectType(found)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>{if(record.title||record.bodyHtml){try{const body=editor.current?.innerHTML||record.bodyHtml;const next={...record,bodyHtml:body,slug:record.slug||slugify(record.title),seoTitle:record.seoTitle||record.title,seoDescription:record.seoDescription||record.summary};saveContent(next,'Auto save');setSaved(`Auto-saved ${new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`)}catch{setSaved('Auto-save tertunda')}}},1800);return()=>clearTimeout(timer)},[record.title,record.summary,record.bodyHtml,record.thumbnail,record.inlineMedia,record.authors,record.seoTitle,record.seoDescription]);
 const issues=useMemo(()=>validateContent(record),[record]);const completion=Math.round((stepLabels.length-new Set(issues.map(x=>x.step)).size)/stepLabels.length*100);const current=validateStep(record,step);
 function selectType(type:ContentType){setRecord(v=>({...v,type,templateId:type,bodyHtml:v.bodyHtml||templates[type]}));setNotice({type:'info',text:`Template ${typeLabels[type]} diterapkan. Struktur tetap dapat diedit.`})}
 function next(){const result=validateStep({...record,bodyHtml:editor.current?.innerHTML||record.bodyHtml},step);if(!result.valid){setNotice({type:'error',text:result.issues.map(x=>x.message).join(' ')});return}setStep(x=>Math.min(6,x+1));setNotice(null)}
 async function save(status:'DRAFT'|'SUBMITTED'='DRAFT'){
  const body=editor.current?.innerHTML||record.bodyHtml;const effectiveStatus=status==='DRAFT'&&editId?record.status:status;const next={...record,bodyHtml:body,status:effectiveStatus,slug:record.slug||slugify(record.title),seoTitle:record.seoTitle||record.title,seoDescription:record.seoDescription||record.summary};
  if(effectiveStatus==='SUBMITTED'){const all=validateContent(next);if(all.length){setStep(all[0].step);setNotice({type:'error',text:`Perbaiki terlebih dahulu: ${all.map(x=>x.message).join(' ')}`});return}}
  try{setBusy(true);const stored=saveContent(next,effectiveStatus==='SUBMITTED'?'Submitted for editorial review':editId?'Article updated':'Manual draft save');setRecord(stored);setSaved(`Tersimpan ${new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`);if(effectiveStatus==='SUBMITTED'){setNotice({type:'success',text:'Artikel dikirim untuk review editorial.'});setTimeout(()=>router.push('/dashboard/author/content'),700)}else setNotice({type:'success',text:'Draft berhasil disimpan.'})}catch{setNotice({type:'error',text:'Penyimpanan browser penuh. Hapus media/draft lama atau gunakan gambar yang lebih kecil.'})}finally{setBusy(false)}
 }
 async function addImage(file:File|undefined,kind:'thumbnail'|'inline'|'videoThumb'){
  if(!file)return;if(kind==='inline'&&record.inlineMedia.length>=MAX_INLINE){setNotice({type:'error',text:'Maksimum 3 gambar isi artikel. Hapus satu gambar sebelum menambah yang baru.'});return}
  try{setBusy(true);const media=await prepareImage(file,kind==='thumbnail'?'thumbnail':'inline');const savedMedia=saveMedia(media);if(kind==='thumbnail')update({thumbnail:savedMedia});else if(kind==='videoThumb')update({customVideoThumbnail:savedMedia});else update({inlineMedia:[...record.inlineMedia,savedMedia].slice(0,MAX_INLINE)});setNotice({type:'success',text:`${file.name} berhasil divalidasi dan dioptimalkan.`})}catch(e){setNotice({type:'error',text:e instanceof Error?e.message:'Gambar gagal diproses.'})}finally{setBusy(false)}
 }
 const yid=youtubeId(record.youtubeUrl||'');
 useEffect(()=>{if(record.videoMethod==='YOUTUBE')update({youtubeId:yid,youtubeThumbnail:yid?`https://i.ytimg.com/vi/${yid}/hqdefault.jpg`:''})},[record.youtubeUrl,record.videoMethod]);
 const setMediaMeta=(kind:'thumbnail'|'inline',index:number,key:keyof MediaMeta,value:string)=>{if(kind==='thumbnail'&&record.thumbnail)update({thumbnail:{...record.thumbnail,[key]:value}});if(kind==='inline')update({inlineMedia:record.inlineMedia.map((m,i)=>i===index?{...m,[key]:value}:m)})};
 return <div className="cms-wizard">
  {notice&&<div className={`cms-notice ${notice.type}`} role="status"><span>{notice.type==='success'?'✓':notice.type==='error'?'!':'i'}</span><b>{notice.text}</b><button onClick={()=>setNotice(null)} aria-label="Tutup">×</button></div>}
  <div className="cms-topbar"><div><span className="eyebrow">AUTHOR EXPERIENCE V2.0.2</span><h1 className="serif">Smart Article Studio</h1><p>{saved} · Kelengkapan editorial {completion}%</p></div><div className="cms-actions"><button className="btn" onClick={()=>save('DRAFT')} disabled={busy}>Simpan Draft</button><button className="btn btn-primary" onClick={()=>save('SUBMITTED')} disabled={busy||issues.length>0}>{issues.length?`Perbaiki ${issues.length} item`:'Kirim untuk Review'}</button></div></div>
  <div className="wizard-steps">{stepLabels.map((s,i)=>{const valid=validateStep(record,i).valid;return <button key={s} className={i===step?'active':valid?'done':''} onClick={()=>setStep(i)}><b>{valid?'✓':i+1}</b><span>{s}</span></button>})}</div>
  <div className="wizard-panel">
   {step===0&&<section><h2>1. Pilih Jenis Konten dan Kerangka Artikel</h2><div className="content-type-grid">{Object.entries(typeLabels).map(([key,label])=><button key={key} className={record.type===key?'selected':''} onClick={()=>selectType(key as ContentType)}><b>{label}</b><span>Kerangka artikel disiapkan otomatis dan dapat diubah.</span></button>)}</div><a className="btn template-center-link" href="/dashboard/author/templates">Unduh Template Artikel →</a></section>}
   {step===1&&<section><h2>2. Informasi Dasar</h2><div className="form-grid"><Field label="Judul artikel *" error={issues.find(x=>x.field==='title')?.message}><input value={record.title} maxLength={140} onChange={e=>update({title:e.target.value,slug:slugify(e.target.value)})}/><small>{record.title.length}/140 karakter · {record.title.trim().split(/\s+/).filter(Boolean).length} kata</small></Field><label><span>Bahasa</span><select value={record.locale} onChange={e=>update({locale:e.target.value as 'id'|'en'})}><option value="id">Bahasa Indonesia</option><option value="en">English</option></select></label><label className="wide"><span>Subjudul</span><input value={record.subtitle} onChange={e=>update({subtitle:e.target.value})}/></label><Field label="Ringkasan *" error={issues.find(x=>x.field==='summary')?.message} wide><textarea rows={5} value={record.summary} onChange={e=>update({summary:e.target.value})}/></Field><label><span>Fakultas</span><input value={record.faculty} onChange={e=>update({faculty:e.target.value})}/></label><label><span>Program Studi</span><input value={record.studyProgram} onChange={e=>update({studyProgram:e.target.value})}/></label><Field label="Mata Kuliah" error={issues.find(x=>x.field==='course')?.message}><input value={record.course} onChange={e=>update({course:e.target.value})}/></Field><label><span>Semester</span><input value={record.semester} onChange={e=>update({semester:e.target.value})}/></label></div></section>}
   {step===2&&<section><h2>3. Penyunting Artikel dan Bantuan Penulisan</h2><div className="editor-ai-layout"><div><div className="editor-toolbar"><button onClick={()=>document.execCommand('undo')}>↶</button><button onClick={()=>document.execCommand('redo')}>↷</button><button onClick={()=>document.execCommand('formatBlock',false,'h2')}>H2</button><button onClick={()=>document.execCommand('formatBlock',false,'h3')}>H3</button><button onClick={()=>document.execCommand('bold')}><b>B</b></button><button onClick={()=>document.execCommand('italic')}><i>I</i></button><button onClick={()=>document.execCommand('insertUnorderedList')}>• List</button><button onClick={()=>document.execCommand('formatBlock',false,'blockquote')}>Quote</button><button onClick={()=>document.execCommand('createLink',false,prompt('URL')||'')}>Link</button></div><div ref={editor} className="rich-editor" contentEditable suppressContentEditableWarning onPaste={e=>{e.preventDefault();const html=e.clipboardData.getData('text/html');const text=e.clipboardData.getData('text/plain');if(html){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('[style]').forEach(el=>{const node=el as HTMLElement;node.style.removeProperty('font-weight');node.style.removeProperty('font-family');node.style.removeProperty('font-size');node.style.removeProperty('line-height')});document.execCommand('insertHTML',false,doc.body.innerHTML)}else document.execCommand('insertText',false,text)}} onInput={e=>update({bodyHtml:e.currentTarget.innerHTML})} dangerouslySetInnerHTML={{__html:record.bodyHtml}}/>{issues.filter(x=>x.step===2).map(x=><p className="field-error" key={x.message}>{x.message}</p>)}</div><aside className="ai-assistant"><span>AI WRITING ASSISTANT</span><h3>Framework aktif</h3><p>Analisis lokal—tidak mengirim naskah ke layanan eksternal.</p>{writingSuggestions(record).map(x=><div key={x}>• {x}</div>)}<button className="btn" onClick={()=>update({bodyHtml:record.bodyHtml+'<h2>Kesimpulan</h2><p>Rangkum temuan, implikasi, dan langkah berikutnya di sini.</p>'})}>Tambahkan kerangka kesimpulan</button></aside></div></section>}
   {step===3&&<section><h2>4. Pengelola Media</h2><div className="media-manager-v2"><MediaBox title="Gambar sampul utama" media={record.thumbnail} required onUpload={f=>addImage(f,'thumbnail')} onDelete={()=>update({thumbnail:undefined})} onMeta={(k,v)=>setMediaMeta('thumbnail',0,k,v)}/><div className="inline-media-zone"><div className="media-zone-head"><div><h3>Gambar dalam artikel</h3><p>Maksimum 3 gambar · JPG, PNG, WebP · maksimal 10 MB sebelum optimasi.</p></div><b>{record.inlineMedia.length}/3</b></div><label className={`dropzone-v2 ${record.inlineMedia.length>=3?'disabled':''}`}><input type="file" accept="image/jpeg,image/png,image/webp" disabled={record.inlineMedia.length>=3} onChange={e=>{void addImage(e.target.files?.[0],'inline');e.currentTarget.value=''}}/><span>＋ Tambah gambar</span></label><div className="media-assets-grid">{record.inlineMedia.map((m,i)=><MediaBox key={m.id||i} title={`Gambar ${i+1}`} media={m} onUpload={f=>replaceInline(record,i,f,addImage,update)} onDelete={()=>update({inlineMedia:record.inlineMedia.filter((_,x)=>x!==i)})} onMeta={(k,v)=>setMediaMeta('inline',i,k,v)}/>)}</div></div></div><div className="video-choice"><h3>Video Pembelajaran</h3><div className="method-tabs"><button className={record.videoMethod==='UPLOAD'?'active':''} onClick={()=>update({videoMethod:'UPLOAD'})}>Upload langsung</button><button className={record.videoMethod==='YOUTUBE'?'active':''} onClick={()=>update({videoMethod:'YOUTUBE'})}>Tautan YouTube</button><button className={record.videoMethod==='NONE'?'active':''} onClick={()=>update({videoMethod:'NONE'})}>Tanpa video</button></div>{record.videoMethod==='UPLOAD'&&<label className="dropzone-v2"><input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>250*1024*1024){setNotice({type:'error',text:'Video maksimum 250 MB.'});return}update({videoFile:{id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,preview:URL.createObjectURL(f)},videoMethod:'UPLOAD'});setNotice({type:'success',text:'Video lolos validasi awal.'})}}/><span>Pilih MP4, WebM, atau MOV</span></label>}{record.videoMethod==='YOUTUBE'&&<div className="youtube-connect"><label><span>URL YouTube</span><input value={record.youtubeUrl||''} onChange={e=>update({youtubeUrl:e.target.value})} placeholder="https://www.youtube.com/watch?v=..."/></label>{yid?<img src={`https://i.ytimg.com/vi/${yid}/hqdefault.jpg`} alt="Pratinjau gambar video"/>:<p className="field-error">Masukkan link YouTube yang valid.</p>}</div>}</div></section>}
   {step===4&&<section><h2>5. Professional Author Profile</h2><div className="form-grid"><Field label="Nama profesional *" error={issues.find(x=>x.field==='authorName')?.message}><input value={record.authors[0]?.name||''} onChange={e=>update({authors:[{...record.authors[0],name:e.target.value}]})}/></Field><Field label="Afiliasi *" error={issues.find(x=>x.field==='affiliation')?.message}><input value={record.authors[0]?.affiliation||''} onChange={e=>update({authors:[{...record.authors[0],affiliation:e.target.value}]})}/></Field><Field label="ORCID" error={issues.find(x=>x.field==='orcid')?.message}><input value={record.authors[0]?.orcid||''} onChange={e=>update({authors:[{...record.authors[0],orcid:e.target.value}]})} placeholder="0000-0000-0000-0000"/></Field><label><span>Google Scholar</span><input value={record.authors[0]?.googleScholar||''} onChange={e=>update({authors:[{...record.authors[0],googleScholar:e.target.value}]})} placeholder="https://scholar.google.com/citations?user=..."/></label><label className="wide"><span>Website</span><input value={record.authors[0]?.website||''} onChange={e=>update({authors:[{...record.authors[0],website:e.target.value}]})}/></label></div><a className="btn" href="/dashboard/author/profile">Kelola foto dan profil lengkap →</a></section>}
   {step===5&&<section><h2>6. Referensi dan Disclosure</h2><div className="form-grid"><Field label="Referensi (satu per baris)" error={issues.find(x=>x.field==='references')?.message} wide><textarea rows={10} value={record.references} onChange={e=>update({references:e.target.value})} placeholder="DOI, URL sumber primer, buku, atau laporan resmi"/></Field><Field label="Pendanaan" wide><textarea rows={3} value={record.funding} onChange={e=>update({funding:e.target.value})} placeholder="Tuliskan sumber pendanaan atau 'Tidak ada pendanaan eksternal'."/></Field><Field label="Konflik Kepentingan" error={issues.find(x=>x.field==='conflict')?.message} wide><textarea rows={3} value={record.conflict} onChange={e=>update({conflict:e.target.value})} placeholder="Contoh: Penulis menyatakan tidak ada konflik kepentingan."/></Field><Field label="Disclosure Penggunaan AI" wide><textarea rows={3} value={record.aiDisclosure} onChange={e=>update({aiDisclosure:e.target.value})} placeholder="Jelaskan penggunaan AI, atau tuliskan bahwa AI tidak digunakan."/></Field></div></section>}
   {step===6&&<section><h2>7. Preview dan Submit</h2><div className="review-readiness"><div><strong>{issues.length===0?'Siap dikirim':`${issues.length} item perlu diperbaiki`}</strong><p>Step 7 hanya menampilkan hasil validasi. Kesalahan dapat diklik untuk kembali ke langkah terkait.</p></div>{issues.map(x=><button key={`${x.step}-${x.message}`} onClick={()=>setStep(x.step)}><b>Langkah {x.step+1}</b><span>{x.message}</span>→</button>)}</div><article className="article-preview-v2">{record.thumbnail?.preview&&<img src={record.thumbnail.preview} alt={record.thumbnail.alt||record.title}/>}<span>{typeLabels[record.type]}</span><h1>{record.title||'Judul artikel'}</h1><p>{record.summary}</p><small>{record.authors[0]?.name} · {record.authors[0]?.affiliation}</small><div dangerouslySetInnerHTML={{__html:record.bodyHtml}}/>{record.inlineMedia.map((m,i)=><figure key={m.id||i}><img src={m.preview} alt={m.alt||`Gambar ${i+1}`}/><figcaption>{m.caption||m.credit}</figcaption></figure>)}</article><button className="btn btn-primary block-button" disabled={issues.length>0||busy} onClick={()=>save('SUBMITTED')}>{issues.length?'Lengkapi semua langkah':'Kirim untuk Review Editorial'}</button></section>}
  </div><div className="wizard-footer"><button className="btn" disabled={step===0} onClick={()=>setStep(x=>x-1)}>← Kembali</button><span>Langkah {step+1} dari 7</span><button className="btn btn-primary" disabled={step===6} onClick={next}>Lanjut →</button></div>
 </div>
}
function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:React.ReactNode}){return <label className={`${wide?'wide ':''}${error?'invalid':''}`}><span>{label}</span>{children}{error&&<small className="field-error">{error}</small>}</label>}
function MediaBox({title,media,required,onUpload,onDelete,onMeta}:{title:string;media?:MediaMeta;required?:boolean;onUpload:(f:File)=>void;onDelete:()=>void;onMeta:(k:keyof MediaMeta,v:string)=>void}){return <article className="media-box-v2"><div className="media-box-title"><h3>{title}{required?' *':''}</h3>{media&&<button onClick={onDelete}>Hapus</button>}</div>{media?.preview?<><div className="media-preview-v2"><img src={media.preview} alt={media.alt||title}/><span>{media.width}×{media.height} · {(media.size/1024).toFixed(0)} KB</span></div><label className="btn replace-media">Ganti<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);e.currentTarget.value=''}}/></label><div className="media-meta-fields"><input value={media.alt||''} onChange={e=>onMeta('alt',e.target.value)} placeholder="Alt text *"/><input value={media.caption||''} onChange={e=>onMeta('caption',e.target.value)} placeholder="Caption"/><input value={media.credit||''} onChange={e=>onMeta('credit',e.target.value)} placeholder="Kredit"/><input value={media.license||''} onChange={e=>onMeta('license',e.target.value)} placeholder="Lisensi"/></div></>:<label className="dropzone-v2"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);e.currentTarget.value=''}}/><span>Unggah gambar</span><small>Validasi ukuran, format, dan resolusi dilakukan langsung.</small></label>}</article>}
async function replaceInline(record:ContentRecord,index:number,file:File,add:(f:File,k:'thumbnail'|'inline'|'videoThumb')=>Promise<void>,update:(p:Partial<ContentRecord>)=>void){try{const media=await prepareImage(file,'inline');saveMedia(media);update({inlineMedia:record.inlineMedia.map((m,i)=>i===index?media:m)})}catch{await add(file,'inline')}}
function writingSuggestions(r:ContentRecord){const plain=r.bodyHtml.replace(/<[^>]+>/g,' ').trim();const out=[];if(plain.split(/\s+/).length<800)out.push('Perdalam bukti, contoh, dan implikasi.');if(!/<h2/i.test(r.bodyHtml))out.push('Tambahkan heading H2 agar mudah dipindai.');if(!/kesimpulan/i.test(plain))out.push('Tambahkan kesimpulan yang tegas.');if(!r.references.trim())out.push('Tambahkan referensi kredibel.');return out.length?out:['Struktur artikel sudah baik. Lakukan penyuntingan akhir.']}
