'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {changeStatus,duplicateContent,exportContentRecord,listContentForAuthor,removeContent,resolveThumbnail,subscribeContent} from '@/lib/cms/store';import BackupManager from './BackupManager';import {ContentRecord,ContentStatus} from '@/lib/cms/types';
import {useAuth} from '@/components/auth/AuthProvider';
const statuses:ContentStatus[]=['DRAFT','READY','SUBMITTED','REVIEW','REVISION','ACCEPTED','SCHEDULED','PUBLISHED','ARCHIVED'];const labels:Record<ContentStatus,string>={DRAFT:'Draf',READY:'Siap',SUBMITTED:'Dikirim',REVIEW:'Sedang Ditinjau',REVISION:'Perlu Revisi',ACCEPTED:'Disetujui',SCHEDULED:'Terjadwal',PUBLISHED:'Terbit',ARCHIVED:'Diarsipkan'};
export default function MyContent(){const {user}=useAuth();const [rows,setRows]=useState<ContentRecord[]>([]),[filter,setFilter]=useState<'ALL'|ContentStatus>('ALL');const load=async()=>{
 try{
  const response=await fetch('/api/cms',{cache:'no-store'});

  if(response.ok){
   const payload=await response.json();
   setRows(
    Array.isArray(payload.content)
     ?payload.content
     :[]
   );
   return;
  }
 }catch{}

 setRows(listContentForAuthor(user?.email));
};useEffect(()=>{void load();const unsub=subscribeContent(()=>void load());window.addEventListener('sn360-content-restored',load);return()=>{unsub();window.removeEventListener('sn360-content-restored',load)}},[user?.email]);const shown=filter==='ALL'?rows:rows.filter(x=>x.status===filter);return <div><div className="cms-topbar"><div><span className="eyebrow">PENGELOLAAN KONTEN</span><h1 className="serif">Konten Saya</h1><p>Kelola artikel, media, status, versi, dan publikasi tanpa membuat ulang konten.</p></div><Link className="btn btn-primary" href="/dashboard/author/create">＋ Buat Konten</Link></div><BackupManager onRestored={load}/><div className="status-tabs"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>Semua ({rows.length})</button>{statuses.map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{labels[s]} ({rows.filter(x=>x.status===s).length})</button>)}</div>{shown.length===0?<div className="empty-state"><b>Belum ada konten.</b><span>Mulai dengan membuat draft baru.</span></div>:<div className="content-table">{shown.map(x=>{const thumb=resolveThumbnail(x);return <article key={x.id}><div className="content-thumb">{thumb?<img src={thumb} alt={x.thumbnail?.alt||x.title}/>:<span>SN360</span>}</div><div className="content-main"><span className={`status ${x.status.toLowerCase()}`}>{labels[x.status]}</span><h3>{x.title||'Tanpa judul'}</h3><p>{x.summary||'Belum ada ringkasan.'}</p><small>{new Date(x.updatedAt).toLocaleString('id-ID')} · {x.versions.length} versi</small><div className="status-timeline-mini">{['DRAFT','SUBMITTED','REVIEW','ACCEPTED','PUBLISHED'].map(s=><i className={statuses.indexOf(x.status)>=statuses.indexOf(s as ContentStatus)?'done':''} key={s}>{s}</i>)}</div></div><div className="content-actions content-actions-expanded"><Link href={`/${x.locale}/article/${x.slug}`} target="_blank">Lihat</Link><Link href={`/dashboard/author/create?edit=${x.id}`}>Edit Artikel</Link><Link href={`/dashboard/author/create?edit=${x.id}&step=3`}>Kelola Media</Link><Link href={`/dashboard/author/content/${x.id}`}>Riwayat</Link><button onClick={()=>{duplicateContent(x.id);load()}}>Duplikat</button><button onClick={()=>exportContentRecord(x.id)}>Unduh</button>{x.status==='DRAFT'&&<button onClick={()=>{changeStatus(x.id,'SUBMITTED','Dikirim untuk ditinjau');load()}}>Kirim Review</button>}{x.status==='PUBLISHED'&&<button onClick={()=>{changeStatus(x.id,'REVISION','Pembaruan diajukan');load()}}>Ajukan Update</button>}<button onClick={()=>{if(confirm('Arsipkan artikel ini?')){changeStatus(x.id,'ARCHIVED','Diarsipkan oleh penulis');load()}}}>Arsipkan</button><button className="danger-link" onClick={()=>{if(confirm('Hapus konten? Tindakan ini tidak dapat dibatalkan.')){removeContent(x.id);load()}}}>Hapus</button></div></article>})}</div>}</div>}