import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getAllArticles,getArticle} from '@/lib/articles';
import {locales,type Locale} from '@/lib/home-data';
import ArticleActions from '@/components/article/ArticleActions';
import ArticleComments from '@/components/article/ArticleComments';
import MathFormula from '@/components/article/MathFormula';
import ReadingProgress from '@/components/article/ReadingProgress';
import AuthorByline from '@/components/article/AuthorByline';
import PublishedArticleClient from '@/components/article/PublishedArticleClient';
import ServerPublishedArticle from '@/components/article/ServerPublishedArticle';
import {getPublishedArticle} from '@/lib/server-publications';
import {absoluteUrl,canonicalArticleUrl,cleanSocialText,getSiteUrl,SITE_NAME,socialImageUrl} from '@/lib/social';

export const dynamic='force-dynamic';
export function generateStaticParams(){return locales.flatMap(locale=>getAllArticles(locale).map(a=>({locale,slug:a.slug})))}
export async function generateMetadata({params}:{params:Promise<{locale:Locale,slug:string}>}):Promise<Metadata>{
 const {locale,slug}=await params;
 const published=await getPublishedArticle(locale,slug);
 const article=getArticle(locale,slug);
 const title=cleanSocialText(published?.openGraphTitle||published?.seoTitle||article?.title||decodeURIComponent(slug).replaceAll('-', ' '),110);
 const description=cleanSocialText(published?.openGraphDescription||published?.seoDescription||article?.summary||(locale==='id'?'Artikel ilmu pengetahuan, pendidikan, teknologi, dan inovasi dari Science News 360.':'Science, education, technology, and innovation from Science News 360.'),200);
 const canonical=published?.canonicalUrl||canonicalArticleUrl(locale,published?.slug||article?.slug||slug);
 const image=published?.socialImageUrl||socialImageUrl(locale,article?.slug||slug,article?.image);
 const publishedAt=published?.publishedAt||'2026-08-04T00:00:00.000Z';
 const modifiedAt=published?.updatedAt||publishedAt;
 const author=published?.author||article?.author||'Science News 360';
 const category=published?.category||article?.category||'Science';
 const tags=published?.tags?.length?published.tags:[category,article?.kind||'Article'];
 return {
  metadataBase:new URL(getSiteUrl()),title:`${title} | Science News 360`,description,
  alternates:{canonical,languages:{id:canonicalArticleUrl('id',published?.slug||article?.slug||slug),en:canonicalArticleUrl('en',published?.slug||article?.slug||slug)}},
  robots:{index:true,follow:true,'max-image-preview':'large','max-snippet':-1,'max-video-preview':-1},
  openGraph:{type:'article',siteName:SITE_NAME,title,description,url:canonical,locale:locale==='id'?'id_ID':'en_US',alternateLocale:locale==='id'?['en_US']:['id_ID'],images:[{url:image,secureUrl:image,width:1200,height:630,alt:published?.socialImageAlt||`${title} — Science News 360`}],publishedTime:publishedAt,modifiedTime:modifiedAt,authors:[author],section:category,tags},
  twitter:{card:'summary_large_image',site:'@ScienceNews360',creator:'@ScienceNews360',title,description,images:[{url:image,alt:published?.socialImageAlt||`${title} — Science News 360`}]},
  other:{'article:published_time':publishedAt,'article:modified_time':modifiedAt,'article:author':author,'article:section':category,'article:tag':tags.join(', ')}
 };
}

export default async function ArticlePage({params}:{params:Promise<{locale:Locale,slug:string}>}){
 const {locale,slug}=await params;if(!locales.includes(locale))notFound();const serverArticle=await getPublishedArticle(locale,slug);if(serverArticle)return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':serverArticle.type==='SCIENCE_NEWS'?'NewsArticle':'Article',headline:serverArticle.title,description:serverArticle.summary,image:[serverArticle.socialImageUrl],datePublished:serverArticle.publishedAt,dateModified:serverArticle.updatedAt,mainEntityOfPage:serverArticle.canonicalUrl,author:{'@type':'Person',name:serverArticle.author},publisher:{'@type':'Organization',name:'Science News 360',logo:{'@type':'ImageObject',url:absoluteUrl('/images/social-default-1200x630.webp')}}})}}/><ServerPublishedArticle article={serverArticle}/></>;const s=getArticle(locale,slug);if(!s)return <PublishedArticleClient locale={locale} slug={slug}/>;
 const related=getAllArticles(locale).filter(x=>x.slug!==slug&&(x.category===s.category||x.kind===s.kind)).slice(0,3);
 const inlineRelated=related.length>=2?related:getAllArticles(locale).filter(x=>x.slug!==slug).slice(0,2);
 const trending=getAllArticles(locale).filter(x=>x.slug!==slug).slice(0,5); const learning=s.kind!=='news';
 const toc=learning?[['learning-outcomes',locale==='id'?'Capaian pembelajaran':'Learning outcomes'],['lesson-summary',locale==='id'?'Ringkasan materi':'Lesson summary'],['core-discussion',locale==='id'?'Pembahasan utama':'Core discussion'],['formula',locale==='id'?'Rumus dan analisis':'Formula and analysis'],['exercise',locale==='id'?'Latihan dan refleksi':'Exercises and reflection'],['references',locale==='id'?'Referensi':'References']]:[['overview',locale==='id'?'Ikhtisar':'Overview'],['evidence',locale==='id'?'Bukti dan konteks':'Evidence and context'],['video',locale==='id'?'Video penjelasan':'Explainer video'],['implications',locale==='id'?'Implikasi':'Implications'],['references',locale==='id'?'Referensi':'References']];
 const jsonLd={"@context":"https://schema.org","@type":learning?'ScholarlyArticle':'NewsArticle',headline:s.title,description:s.summary,image:s.image,datePublished:'2026-08-04',dateModified:'2026-08-04',author:{"@type":"Person",name:s.author},publisher:{"@type":"Organization",name:'Science News 360'},identifier:s.doi};
 return <main className="production-article"><ReadingProgress/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <div className="shell article-breadcrumb"><Link href={`/${locale}`}>{locale==='id'?'Beranda':'Home'}</Link><span>›</span>{learning&&<><Link href={`/${locale}/education/course-materials`}>{locale==='id'?'Materi Kuliah':'Course Materials'}</Link><span>›</span></>}<span>{s.category}</span></div>
  <header className="shell article-premium-header"><div className="article-kickers"><span className="eyebrow">{s.category}</span>{learning&&<span className="content-kind">{s.kind.replaceAll('-',' ')}</span>}<span className="verified-label">✓ {locale==='id'?'Ditinjau editorial':'Editorially reviewed'}</span></div><h1>{s.title}</h1><p>{s.summary}</p><AuthorByline fallbackName={s.author} fallbackInstitution={s.institution} locale={locale} publishedAt={s.publishedAt ?? "2026-08-04T00:00:00.000Z"} updatedAt={s.updatedAt ?? s.publishedAt ?? "2026-08-04T00:00:00.000Z"} time={s.time} doi={s.doi ?? "Pending"}/><ArticleActions title={s.title} locale={locale} canonicalUrl={canonicalArticleUrl(locale,s.slug)}/></header>
  <figure className="shell article-premium-hero"><img src={s.image} alt={`${s.title} — Science News 360`}/><figcaption><span>Science News 360 Visual Desk</span><span>{locale==='id'?'Ilustrasi editorial untuk artikel ini.':'Editorial illustration for this article.'}</span></figcaption></figure>
  <div className="shell article-production-grid"><aside className="article-toc"><div className="toc-sticky"><span>ON THIS PAGE</span><h3>{locale==='id'?'Daftar Isi':'Table of Contents'}</h3>{toc.map(([id,label],i)=><a key={id} href={`#${id}`}><b>{String(i+1).padStart(2,'0')}</b>{label}</a>)}<div className="print-hint">{locale==='id'?'Gunakan tombol PDF di atas untuk mencetak atau menyimpan sebagai PDF.':'Use the PDF button above to print or save as PDF.'}</div></div></aside>
  <article className="article-reading-column">
   {learning&&<section className="course-facts premium"><div><span>{locale==='id'?'Fakultas':'Faculty'}</span><b>{s.faculty}</b></div><div><span>{locale==='id'?'Program Studi':'Study Program'}</span><b>{s.program}</b></div><div><span>{locale==='id'?'Mata Kuliah':'Course'}</span><b>{s.course}</b></div><div><span>{locale==='id'?'Jenjang/Semester':'Level/Semester'}</span><b>{s.level} · {s.semester}</b></div></section>}
   {learning?<>
    <section id="learning-outcomes" className="article-content-section"><div className="article-section-label">LEARNING OBJECTIVES</div><h2>{locale==='id'?'Capaian Pembelajaran':'Learning Outcomes'}</h2><ul className="outcome-list">{s.learningOutcomes?.map(x=><li key={x}>{x}</li>)||<><li>{locale==='id'?'Memahami konsep utama materi.':'Understand the main concepts.'}</li><li>{locale==='id'?'Menerapkan konsep pada contoh dan latihan.':'Apply the concepts to examples and exercises.'}</li></>}</ul></section>
    <section id="lesson-summary" className="article-content-section"><div className="key-takeaway"><span>KEY TAKEAWAY</span><p>{s.summary} {locale==='id'?'Materi ini dapat dipadukan dengan diskusi kelas, latihan mandiri, dan evaluasi formatif.':'This material can be combined with classroom discussion, independent exercises, and formative assessment.'}</p></div></section>
    <section id="core-discussion" className="article-content-section"><div className="article-section-label">CORE DISCUSSION</div><h2>{locale==='id'?'Pembahasan Utama':'Core Discussion'}</h2><p>{locale==='id'?'Pembelajaran dimulai dari definisi dan asumsi dasar, kemudian bergerak menuju hubungan antarvariabel, interpretasi konseptual, dan penerapan pada kasus nyata. Setiap hasil harus dibaca secara kritis dengan memperhatikan konteks, kualitas data, dan keterbatasan metode.':'The lesson begins with definitions and core assumptions before moving to relationships among variables, conceptual interpretation, and applications to real cases. Every result should be critically assessed in light of context, data quality, and methodological limitations.'}</p><blockquote>{locale==='id'?'Pemahaman yang kuat tidak berhenti pada kemampuan menghafal rumus, tetapi pada kemampuan menjelaskan makna ekonomi dan implikasinya.':'Strong understanding goes beyond memorizing formulas; it requires explaining their meaning and implications.'}</blockquote><h3>{locale==='id'?'Contoh interpretasi':'Interpretation example'}</h3><p>{locale==='id'?'Ketika satu variabel berubah, analisis tidak hanya mencatat arah perubahan, tetapi juga menjelaskan mekanisme, asumsi yang digunakan, dan kelompok yang menerima dampaknya.':'When one variable changes, analysis should explain not only the direction of change, but also the mechanism, assumptions, and affected groups.'}</p></section>{inlineRelated[0]&&<aside className="inline-related-link"><span>{locale==='id'?'BACA ARTIKEL TERKAIT':'READ RELATED ARTICLE'}</span><Link href={`/${locale}/article/${inlineRelated[0].slug}`}><strong>{inlineRelated[0].title}</strong><em>{locale==='id'?'Buka artikel →':'Open article →'}</em></Link></aside>}
    <section id="formula" className="article-content-section"><div className="article-section-label">QUANTITATIVE NOTE</div><h2>{locale==='id'?'Rumus dan Analisis':'Formula and Analysis'}</h2><MathFormula formula={'Y = C(Y-T) + I(r) + G'} label={locale==='id'?'Contoh persamaan keseimbangan pasar barang, dirender menggunakan KaTeX ketika koneksi tersedia.':'Example goods-market equilibrium equation, rendered with KaTeX when connectivity is available.'}/><div className="data-table-wrap"><table><caption>{locale==='id'?'Contoh skenario analisis':'Illustrative analysis scenario'}</caption><thead><tr><th>{locale==='id'?'Skenario':'Scenario'}</th><th>G</th><th>Y</th><th>r</th><th>{locale==='id'?'Interpretasi':'Interpretation'}</th></tr></thead><tbody><tr><td>Baseline</td><td>100</td><td>1,000</td><td>5%</td><td>{locale==='id'?'Keseimbangan awal':'Initial equilibrium'}</td></tr><tr><td>{locale==='id'?'Ekspansi fiskal':'Fiscal expansion'}</td><td>130</td><td>1,080</td><td>5.8%</td><td>{locale==='id'?'Output dan suku bunga meningkat':'Output and interest rate rise'}</td></tr></tbody></table></div></section>
    <section id="exercise" className="article-content-section"><div className="article-section-label">PRACTICE</div><h2>{locale==='id'?'Latihan dan Refleksi':'Exercises and Reflection'}</h2><ol className="exercise-list"><li>{locale==='id'?'Jelaskan konsep utama dengan bahasa Anda sendiri.':'Explain the main concept in your own words.'}</li><li>{locale==='id'?'Berikan satu contoh penerapan pada konteks Indonesia.':'Provide one application in the Indonesian context.'}</li><li>{locale==='id'?'Identifikasi keterbatasan konsep atau metode yang digunakan.':'Identify one limitation of the concept or method.'}</li></ol></section>
   </>:<>
    <section id="overview" className="article-content-section"><div className="article-section-label">OVERVIEW</div><p className="article-lead">{locale==='id'?'Perkembangan ini menunjukkan bahwa inovasi ilmiah tidak berdiri sendiri. Dampaknya bergantung pada kualitas data, tata kelola, kapasitas manusia, serta kemampuan institusi menerjemahkan temuan menjadi manfaat publik.':'This development shows that scientific innovation does not stand alone. Its impact depends on data quality, governance, human capacity, and institutions’ ability to translate findings into public value.'}</p><p>{locale==='id'?'Di universitas, penggunaan kecerdasan buatan berkembang dari otomatisasi administrasi menuju dukungan penelitian, pengembangan materi pembelajaran, analisis data, dan komunikasi ilmiah. Namun, penerapan yang bertanggung jawab memerlukan verifikasi manusia dan transparansi metode.':'At universities, artificial intelligence is moving beyond administrative automation toward research support, learning-content development, data analysis, and science communication. Responsible use, however, requires human verification and methodological transparency.'}</p></section>
    <section id="evidence" className="article-content-section"><div className="article-section-label">EVIDENCE & CONTEXT</div><h2>{locale==='id'?'Bukti, Metode, dan Konteks':'Evidence, Methods, and Context'}</h2><p>{locale==='id'?'Klaim ilmiah yang kuat harus dapat ditelusuri kembali kepada sumber primer, metode pengumpulan data, prosedur analisis, dan batas generalisasi. Artikel populer tidak boleh menghilangkan ketidakpastian yang melekat pada penelitian.':'Strong scientific claims must be traceable to primary sources, data-collection methods, analytical procedures, and limits of generalization. Popular articles should not erase the uncertainty inherent in research.'}</p><blockquote>{locale==='id'?'Kecepatan teknologi tidak boleh menggantikan ketelitian ilmiah.':'Technological speed must not replace scientific rigor.'}</blockquote><div className="data-table-wrap"><table><caption>{locale==='id'?'Kerangka evaluasi penggunaan AI akademik':'Academic AI-use evaluation framework'}</caption><thead><tr><th>{locale==='id'?'Dimensi':'Dimension'}</th><th>{locale==='id'?'Pertanyaan audit':'Audit question'}</th><th>{locale==='id'?'Status':'Status'}</th></tr></thead><tbody><tr><td>{locale==='id'?'Akurasi':'Accuracy'}</td><td>{locale==='id'?'Apakah keluaran diverifikasi dengan sumber primer?':'Was the output verified against primary sources?'}</td><td>{locale==='id'?'Wajib':'Required'}</td></tr><tr><td>{locale==='id'?'Transparansi':'Transparency'}</td><td>{locale==='id'?'Apakah bantuan AI diungkapkan?':'Was AI assistance disclosed?'}</td><td>{locale==='id'?'Wajib':'Required'}</td></tr><tr><td>{locale==='id'?'Privasi':'Privacy'}</td><td>{locale==='id'?'Apakah data sensitif dilindungi?':'Was sensitive data protected?'}</td><td>{locale==='id'?'Wajib':'Required'}</td></tr></tbody></table></div></section>{inlineRelated[0]&&<aside className="inline-related-link"><span>{locale==='id'?'BACA ARTIKEL TERKAIT':'READ RELATED ARTICLE'}</span><Link href={`/${locale}/article/${inlineRelated[0].slug}`}><strong>{inlineRelated[0].title}</strong><em>{locale==='id'?'Buka artikel →':'Open article →'}</em></Link></aside>}
    <section id="video" className="article-content-section"><div className="article-section-label">WATCH SCIENCE</div><h2>{locale==='id'?'Video Penjelasan':'Explainer Video'}</h2><div className="video-embed"><iframe src={`https://www.youtube-nocookie.com/embed/${s.videoId||'M7lc1UVf-VE'}`} title={s.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><p className="media-caption">{locale==='id'?'Video dapat diganti oleh editor hanya dengan memasukkan ID atau tautan YouTube.':'Editors can replace this video by entering a YouTube ID or link.'}</p></section>
    <section id="implications" className="article-content-section"><div className="article-section-label">WHY IT MATTERS</div><h2>{locale==='id'?'Implikasi untuk Kampus dan Masyarakat':'Implications for Campuses and Society'}</h2><p>{locale==='id'?'Manfaat terbesar muncul ketika teknologi digunakan untuk memperkuat kapasitas dosen, peneliti, dan mahasiswa—bukan menghilangkan pertimbangan manusia. Universitas perlu memiliki kebijakan integritas, literasi AI, perlindungan data, dan mekanisme audit yang dapat diuji.':'The greatest benefits emerge when technology strengthens the capacity of lecturers, researchers, and students rather than displacing human judgment. Universities need integrity policies, AI literacy, data protection, and auditable oversight.'}</p></section>
   </>}
   {inlineRelated[1]&&<aside className="inline-related-link article-end-related"><span>{locale==='id'?'BACA ARTIKEL TERKAIT':'READ RELATED ARTICLE'}</span><Link href={`/${locale}/article/${inlineRelated[1].slug}`}><strong>{inlineRelated[1].title}</strong><em>{locale==='id'?'Buka artikel →':'Open article →'}</em></Link></aside>}
   <section id="references" className="article-content-section references-section"><div className="article-section-label">REFERENCES</div><h2>{locale==='id'?'Referensi dan Sitasi':'References and Citation'}</h2><ol><li>Science News 360 Editorial Research Desk. (2026). <i>{s.title}</i>. DOI: <a href={`https://doi.org/${s.doi}`}>{s.doi}</a>.</li><li>UNESCO. (2023). <i>Guidance for generative AI in education and research</i>.</li><li>National Academies of Sciences. (2019). <i>Reproducibility and Replicability in Science</i>.</li></ol><div className="citation-box"><span>APA CITATION</span><code>{s.citation}</code></div></section>
   <ArticleComments locale={locale}/>
  </article>
  <aside className="article-right-sidebar"><div className="sidebar-card author-profile-card"><div className="author-large-avatar">{s.author.charAt(0)}</div><span>ABOUT THE AUTHOR</span><h3>{s.author}</h3><p>{s.institution}</p><p>{locale==='id'?'Kontributor Science News 360 pada bidang ilmu pengetahuan, pendidikan, dan penelitian.':'Science News 360 contributor covering science, education, and research.'}</p><Link href={`/${locale}/authors`}>{locale==='id'?'Lihat profil penulis →':'View author profile →'}</Link></div><div className="sidebar-card trending-sidebar"><span>TRENDING NOW</span><h3>{locale==='id'?'Paling Banyak Dibaca':'Most Read'}</h3>{trending.map((x,i)=><Link href={`/${locale}/article/${x.slug}`} key={x.slug}><b>{String(i+1).padStart(2,'0')}</b><div><em>{x.category}</em><strong>{x.title}</strong></div></Link>)}</div><div className="sidebar-card download-card"><span>OFFLINE READING</span><h3>{locale==='id'?'Simpan artikel ini':'Save this article'}</h3><p>{locale==='id'?'Gunakan tombol PDF pada toolbar untuk membuka mode cetak, kemudian pilih Save as PDF.':'Use the PDF toolbar button to open print mode, then select Save as PDF.'}</p></div></aside>
  </div>
  {related.length>0&&<section className="shell related-section premium-related"><div className="section-head"><div><span>CONTINUE READING</span><h2>{locale==='id'?'Artikel Terkait':'Related Articles'}</h2></div></div><div className="news-grid">{related.map(x=><article className="story-card" key={x.slug}><Link className="story-image" href={`/${locale}/article/${x.slug}`}><img src={x.image} alt={x.title}/><span>{x.category}</span></Link><div className="story-copy"><h3><Link href={`/${locale}/article/${x.slug}`}>{x.title}</Link></h3><p>{x.summary}</p><small>{x.author} · {x.time}</small></div></article>)}</div></section>}
 </main>
}
